export const data = [{
    id: 1,
    title: 'V chem moya vera',
    author: 'L.N. Tolstoy',
    price: 45,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about: 'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот только что вошёл и сел писать. Тут всё у нас хорошо, весна вовсю, снег ещё не сошёл, но вроде бы сходит, на дороге намёрзло много, а калитку я еле отодрал — вон как пристыл внизу ледок то! Так что вошёл когда, сразу трубы проверил и понял что целы слава Богу. Ну и действительно — зима то не очень сурова была больше двадцати двух и не было кажется, а для нас это прямо благодать — и яблонки молодые и розы ваши и опять же чтоб трубы не разорвало. Но ничего, всё обошлось, всё тут хорошо. fdfdfdfdfdf dfdfdfd  fgdhjkfg jhdgfhjkdgfh  jkdfjkdhf jkdhfjydgnbfvdndnfkdfndf,jn  gh mnfdj  fh dkjf fhh hbfkyh f',},
    
{
    id: 2,
    title: 'Atomic Habits',
    author: 'J. Clear',
    price: 45,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот только что вошёл и сел писать. Тут всё у нас хорошо, весна вовсю, снег ещё не сошёл, но вроде бы сходит, на дороге намёрзло много, а калитку я еле отодрал — вон как пристыл внизу ледок то! Так что вошёл когда, сразу трубы проверил и понял что целы слава Богу. Ну и действительно — зима то не очень сурова была больше двадцати двух и не было кажется, а для нас это прямо благодать — и яблонки молодые и розы ваши и опять же чтоб трубы не разорвало. Но ничего, всё обошлось, всё тут хорошо.'},
{
    id: 3,
    title: 'V chem moya vera',
    author: 'L.N. Tolstoy',
    price: 32,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg'},
{
    id: 4,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 5,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 6,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 7,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 8,
    title: 'V chem moya vera',
    author: 'L.N. Tolstoy',
    price: 32,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg'},
{
    id: 9,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 10,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 11,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 12,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 13,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 13,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 13,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 12,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 13,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 13,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 13,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 12,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 13,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 13,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 13,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 12,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 13,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 13,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'},
{
    id: 13,
    title: 'What I believe',
    author: 'L.N. Tolstoy',
    price: 24,
    coverImage: 'https://s1.livelib.ru/boocover/1000005935/200/e9f3/boocover.jpg',
    about:'Здравствуйте дорогой Мартин Алексеич! Пишу вам сразу по приезду, прямо вот'}

]

export const dataCount = data.length

